name: kids-story-aws
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - openai
  - httpx
  - boto3
  - python-dotenv
  - pillow
  - alembic
  - fastapi
  - uvicorn
  - celery
  - redis
  - sqlalchemy
  - asyncpg
  - psycopg2-binary
  - pydantic
  - ruff
  - pytest
