"""add_language_support_to_pages

Revision ID: 37d529d80570
Revises: 6a8fb1f45dcc
Create Date: 2025-06-01 19:27:05.971274

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "37d529d80570"
down_revision: Union[str, None] = "6a8fb1f45dcc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    supportedlanguage_enum = sa.Enum(
        "ENGLISH",
        "SPANISH",
        "CHINESE",
        "FRENCH",
        "PORTUGUESE",
        name="supportedlanguage",
    )
    supportedlanguage_enum.create(op.get_bind())

    # Add the column with default value
    op.add_column(
        "pages",
        sa.Column(
            "language", supportedlanguage_enum, nullable=False, server_default="ENGLISH"
        ),
    )

    # Remove the server default after adding the column
    op.alter_column("pages", "language", server_default=None)

    op.create_unique_constraint(
        "unique_page_per_language", "pages", ["book_id", "order", "language"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_page_per_language", "pages", type_="unique")
    op.drop_column("pages", "language")

    # Drop the enum type
    supportedlanguage_enum = sa.Enum(
        "ENGLISH",
        "SPANISH",
        "CHINESE",
        "FRENCH",
        "PORTUGUESE",
        name="supportedlanguage",
    )
    supportedlanguage_enum.drop(op.get_bind())
    # ### end Alembic commands ###
