"""add_difficulty_level_and_readability_score

Revision ID: 6bb1d7b8bd2c
Revises: 37d529d80570
Create Date: 2025-06-04 21:06:41.436559

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6bb1d7b8bd2c"
down_revision: Union[str, None] = "37d529d80570"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add difficulty_level column with default value of 2 (Level 2 - Age 6)
    op.add_column(
        "books",
        sa.Column("difficulty_level", sa.Integer(), nullable=False, server_default="2"),
    )
    op.add_column(
        "books", sa.Column("calculated_readability_score", sa.Float(), nullable=True)
    )

    # Remove server_default after adding the column (we want default only for new records)
    op.alter_column("books", "difficulty_level", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "calculated_readability_score")
    op.drop_column("books", "difficulty_level")
    # ### end Alembic commands ###
